Update compose and environment vars
NonaSoftware/Neptune pull request #1
Opened 2022-08-08 06:02 UTC by georgemjohnson11

This with a minor update to 3Duf which allowed me to successfully build and setup using `docker-compose --env-file Fluigi-Cloud/.env up --build`

2022-08-08 06:03 UTC, georgemjohnson11 commented on docker-compose.yml
> +      depends_on:
This prevents Neptune from coming up before other services start

2022-08-08 06:03 UTC, georgemjohnson11 commented on setup.sh
> +npm install --legacy-peer-deps
This stops conflicts from happening when node wants you to upgrade packages

2022-08-08 06:04 UTC, georgemjohnson11 commented on Dockerfile
> +RUN git clone https://github.com/yyuu/pyenv.git .pyenv
git URLS require SSH keys which aren't needed

2022-08-10 01:41 UTC, rkrishnasanka commented on Fluigi-Cloud/.env
> +NEPTUNE_AWS_URL="s3local:9001"
I believe `9001` would be the web console and 9000 is the API endpoint

2022-08-10 01:43 UTC, rkrishnasanka requested changes
@georgemjohnson11 If the 9001 port is correct, I think we can do the merge.

2022-08-15 16:49 UTC, merged